<?php
if (($lymcoin_slider_sc = lymcoin_get_theme_option('front_page_title_shortcode')) != '' && strpos($lymcoin_slider_sc, '[')!==false && strpos($lymcoin_slider_sc, ']')!==false) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider"><?php
		// Add anchor
		$lymcoin_anchor_icon = lymcoin_get_theme_option('front_page_title_anchor_icon');	
		$lymcoin_anchor_text = lymcoin_get_theme_option('front_page_title_anchor_text');	
		if ((!empty($lymcoin_anchor_icon) || !empty($lymcoin_anchor_text)) && shortcode_exists('trx_sc_anchor')) {
			echo do_shortcode('[trx_sc_anchor id="front_page_section_title"'
											. (!empty($lymcoin_anchor_icon) ? ' icon="'.esc_attr($lymcoin_anchor_icon).'"' : '')
											. (!empty($lymcoin_anchor_text) ? ' title="'.esc_attr($lymcoin_anchor_text).'"' : '')
											. ']');
		}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode($lymcoin_slider_sc);
	?></div><?php

} else {

	?><div class="front_page_section front_page_section_title<?php
				$lymcoin_scheme = lymcoin_get_theme_option('front_page_title_scheme');
				if (!lymcoin_is_inherit($lymcoin_scheme)) echo ' scheme_'.esc_attr($lymcoin_scheme);
				echo ' front_page_section_paddings_'.esc_attr(lymcoin_get_theme_option('front_page_title_paddings'));
			?>"<?php
			$lymcoin_css = '';
			$lymcoin_bg_image = lymcoin_get_theme_option('front_page_title_bg_image');
			if (!empty($lymcoin_bg_image)) 
				$lymcoin_css .= 'background-image: url('.esc_url(lymcoin_get_attachment_url($lymcoin_bg_image)).');';
			if (!empty($lymcoin_css))
				echo ' style="' . esc_attr($lymcoin_css) . '"';
	?>><?php
		// Add anchor
		$lymcoin_anchor_icon = lymcoin_get_theme_option('front_page_title_anchor_icon');	
		$lymcoin_anchor_text = lymcoin_get_theme_option('front_page_title_anchor_text');	
		if ((!empty($lymcoin_anchor_icon) || !empty($lymcoin_anchor_text)) && shortcode_exists('trx_sc_anchor')) {
			echo do_shortcode('[trx_sc_anchor id="front_page_section_title"'
											. (!empty($lymcoin_anchor_icon) ? ' icon="'.esc_attr($lymcoin_anchor_icon).'"' : '')
											. (!empty($lymcoin_anchor_text) ? ' title="'.esc_attr($lymcoin_anchor_text).'"' : '')
											. ']');
		}
		?>
		<div class="front_page_section_inner front_page_section_title_inner<?php
			if (lymcoin_get_theme_option('front_page_title_fullheight'))
				echo ' lymcoin-full-height sc_layouts_flex sc_layouts_columns_middle';
			?>"<?php
				$lymcoin_css = '';
				$lymcoin_bg_mask = lymcoin_get_theme_option('front_page_title_bg_mask');
				$lymcoin_bg_color = lymcoin_get_theme_option('front_page_title_bg_color');
				if (!empty($lymcoin_bg_color) && $lymcoin_bg_mask > 0)
					$lymcoin_css .= 'background-color: '.esc_attr($lymcoin_bg_mask==1
																		? $lymcoin_bg_color
																		: lymcoin_hex2rgba($lymcoin_bg_color, $lymcoin_bg_mask)
																	).';';
				if (!empty($lymcoin_css))
					echo ' style="' . esc_attr($lymcoin_css) . '"';
		?>>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$lymcoin_caption = lymcoin_get_theme_option('front_page_title_caption');
				if (!empty($lymcoin_caption) || (current_user_can('edit_theme_options') && is_customize_preview())) {
					?><h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo !empty($lymcoin_caption) ? 'filled' : 'empty'; ?>"><?php echo wp_kses($lymcoin_caption, 'lymcoin_kses_content'); ?></h1><?php
				}
			
				// Description (text)
				$lymcoin_description = lymcoin_get_theme_option('front_page_title_description');
				if (!empty($lymcoin_description) || (current_user_can('edit_theme_options') && is_customize_preview())) {
					?><div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo !empty($lymcoin_description) ? 'filled' : 'empty'; ?>"><?php echo wp_kses(wpautop($lymcoin_description), 'lymcoin_kses_content'); ?></div><?php
				}
				
				// Buttons
				if (lymcoin_get_theme_option('front_page_title_button1_link')!='' || lymcoin_get_theme_option('front_page_title_button2_link')!='') {
					?><div class="front_page_section_buttons front_page_section_title_buttons"><?php
						lymcoin_show_layout(lymcoin_customizer_partial_refresh_front_page_title_button1_link());
						lymcoin_show_layout(lymcoin_customizer_partial_refresh_front_page_title_button2_link());
					?></div><?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}